### ISSUE TITLE
ES6 module in dist does not import bootstrap before using it

### ISSUE THREAD

**Issue by mildred** [use-bootstrap/use-bootstrap-select#1]
I'm using use-bootstrap-select as an ES6 module, directly without any bundler like webpack or anything. The problem with the file `dist/use-bootstrap-select.mjs` is that it uses bootstrap (`bootstrap.Dropdown.getOrCreateInstance(dropdownToggle)`) but the `bootstrap` is never imported.

Either the ES6 module should import the bootstrap, and if the import name is not correct, there are always importmaps to fix that, or an alternative is to have the `UseBootstrapSelect()` tajke an optional parameter with bootstrap .

edit: Workaround would be :

```js
import bootstrap from 'bootstrap.js'
window.bootstrap = bootstrap
```

**Comment by erwinheldy** [comment]
Fixed in v1.0.1

Now you can use:
```javascript
import * as bootstrap from 'bootstrap.esm.js'

UseBootstrapSelect(document.getElementById('example'), bootstrap)

```
