### ISSUE TITLE
[Feature] Don't launch drop-down when clearing an item.

### ISSUE THREAD

**Issue by pardeyke** [use-bootstrap/use-bootstrap-select#13]
I think when just want to remove one or two items and not add others, the dropdown should not be shown automatically.
Or maybe make it optional: `data-show-dropdown-on-clear="false"`

**Comment by erwinheldy** [comment]
If the dropdown is closed, then when you delete one or two items the dropdown will still remain closed

**Comment by pardeyke** [comment]
My bad. You'r right. But when `data-searchable="true"` and you then click X the dropdown will open...
