### ISSUE TITLE
Usage without npm?

### ISSUE THREAD

**Issue by cuthulino** [use-bootstrap/use-bootstrap-select#7]
Hello,

I am searching a nice multi select plugin for bootstrap 5 and found this one.
My project is a django based one and without the use of npm.
Is it possible to use it without npm? Just include then .min.js and .min.css?

thank you

**Comment by erwinstone** [comment]
Hello,

Yes you can use it directly:
https://cdn.jsdelivr.net/npm/use-bootstrap-select@1.1.0/dist/

**Comment by erwinheldy** [comment]
Hello,

Yes you can use it directly:
https://cdn.jsdelivr.net/npm/use-bootstrap-select@1.1.0/dist/
