### ISSUE TITLE
Language text

### ISSUE THREAD

**Issue by lucasrohers** [use-bootstrap/use-bootstrap-select#8]
Is it possible to add the "Search" text for editing, send a personalized one?

Furthermore, would a standalone version be possible, with just CSS and JS?

**Comment by erwinheldy** [comment]
I'm sorry, I'm still not clear on the meaning. Could you please explain it in more detail or provide an example to clarify?

If you want a standalone version without bootstrap css, you can use tom-select

**Comment by lucasrohers** [comment]
You have added the Language feature to the results text.
It would be nice to add to the text "SEARCH" too

**Comment by erwinheldy** [comment]
you can use placeholders for that

```html
<select id="example" class="form-select" data-searchable="true">
  <option value="">Search...</option>
  <option value="apple">Apple</option>
  <option value="banana">Banana</option>
  <option value="grape">Grape</option>
  <option value="kiwi">Kiwi</option>
  <option value="orange">Orange</option>
</select>

<script>
  const example = new UseBootstrapSelect(document.getElementById('example'))
</script>
```

**Comment by lucasrohers** [comment]
![image](https://github.com/use-bootstrap/use-bootstrap-select/assets/11723065/c7080052-5795-4912-9455-e4b4a1e3d6bc)

check the image. What i would like it is the plugin has, if possible, to change the text in Search. Exact the same of "noResultsText"
