### ISSUE TITLE
Trigger Dropdown/Focus with JavaScript

### ISSUE THREAD

**Issue by MichaelGeil** [use-bootstrap/use-bootstrap-select#9]
Is it possible to trigger the rendered dropdown with JavaScript?
I have tried several ways for trigger the visibility, but I guess there is one flag that won't be set. If I then click outside the dropdown, it won't be closed until I clicked one time on the rendered div-container.

Which event set the component state for example to isOpen, so that the outside click closed the dropdown automaticly?

The original <label>-Tag doesn't triggered the dropdown's visibility as well.

**Comment by erwinheldy** [comment]
Try updating to version 2.1.0, I've added new methods: `show`, `hide`, `toggle`

**Comment by MichaelGeil** [comment]
Thank you! I will try it today.
I found a typo in my last post. The last sentence should read: The original <label>-Tag doesn't triggered the dropdown's visibility as well. It set only the focus to the rendered dropdown.

**Comment by MichaelGeil** [comment]
the new functions only trigger the visibility from the dropdown. However, the focus is not set on the input field. The focus is only on the input field when you click again. Is it possible to set the focus as well?

**Comment by erwinheldy** [comment]
I've fixed it, please try version 2.1.1

**Comment by MichaelGeil** [comment]
Thank you very much. It works well.
